# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

    User.create(season_id: 1, team_id: 1, username: "aaa", password: "aaa")
    User.create(season_id: 1, team_id: 2, username: "bbb", password: "bbb")    
    User.create(season_id: 1, team_id: 3, username: "ccc", password: "ccc")    
    User.create(season_id: 1, team_id: 4, username: "ddd", password: "ddd")

    Season.create(number: 1)

    Team.create(name: "Mighty Ducks", hometown: "Anaheim")
    Team.create(name: "Bruins", hometown: "Boston")
    Team.create(name: "Sabres", hometown: "Buffalo")
    Team.create(name: "Flames", hometown: "Calgary")
    Team.create(name: "Blackhawks", hometown: "Chicago")
    Team.create(name: "Stars", hometown: "Dallas")
    Team.create(name: "Red Wings", hometown: "Detroit")
    Team.create(name: "Oilers", hometown: "Edmonton")
    Team.create(name: "Whalers", hometown: "Hartford")
    Team.create(name: "Panthers", hometown: "Florida")
    Team.create(name: "Kings", hometown: "Los Angeles")
    Team.create(name: "Canadiens", hometown: "Montreal")
    Team.create(name: "Devils", hometown: "New Jersey")
    Team.create(name: "Islanders", hometown: "New York")
    Team.create(name: "Rangers", hometown: "New York")
    Team.create(name: "Senators", hometown: "Ottawa")
    Team.create(name: "Flyers", hometown: "Philadelphia")
    Team.create(name: "Penguins", hometown: "Pittsburgh")
    Team.create(name: "Nordiques", hometown: "Quebec")
    Team.create(name: "Sharks", hometown: "San Jose")
    Team.create(name: "Blues", hometown: "St. Louis")
    Team.create(name: "Lightning", hometown: "Tampa Bay")
    Team.create(name: "Maple Leafs", hometown: "Toronto")
    Team.create(name: "Canucks", hometown: "Vancouver")
    Team.create(name: "Capitals", hometown: "Washington")
    Team.create(name: "Jets", hometown: "Winnipeg")


    Player.create(name: "Mario Lemieux", rating: 100, position: "F")
    Player.create(name: "Alexander Mogilny", rating: 96, position: "F")
    Player.create(name: "Steve Yzerman", rating: 95, position: "F")
    Player.create(name: "Adam Oates", rating: 93, position: "F")
    Player.create(name: "Pat LaFontaine", rating: 91, position: "F")
    Player.create(name: "Pavel Bure", rating: 90, position: "F")
    Player.create(name: "Teemu Selanne", rating: 90, position: "F")
    Player.create(name: "Jeremy Roenick", rating: 89, position: "F")
    Player.create(name: "Wayne Gretzky", rating: 87, position: "F")
    Player.create(name: "Steve Larmer", rating: 86, position: "F")
    Player.create(name: "Theoren Fleury", rating: 86, position: "F")
    Player.create(name: "Cam Neely", rating: 86, position: "F")
    Player.create(name: "Luc Robitaille", rating: 85, position: "F")
    Player.create(name: "Mark Messier", rating: 85, position: "F")
    Player.create(name: "Mike Gartner", rating: 85, position: "F")
    Player.create(name: "Gary Roberts", rating: 85, position: "F")
    Player.create(name: "Eric Lindros", rating: 84, position: "F")
    Player.create(name: "Sergei Fedorov", rating: 84, position: "F")
    Player.create(name: "Mark Recchi", rating: 83, position: "F")
    Player.create(name: "Joe Sakic", rating: 83, position: "F")
    Player.create(name: "Pierre Turgeon", rating: 82, position: "F")
    Player.create(name: "Mike Modano", rating: 82, position: "F")
    Player.create(name: "Brett Hull", rating: 81, position: "F")
    Player.create(name: "Tomas Sandstrom", rating: 80, position: "F")
    Player.create(name: "Esa Tikkanen", rating: 80, position: "F")
    Player.create(name: "Jaromir Jagr", rating: 80, position: "F")
    Player.create(name: "Dino Ciccarelli", rating: 80, position: "F")
    Player.create(name: "Kirk Muller", rating: 80, position: "F")
    Player.create(name: "Mats Sundin", rating: 79, position: "F")
    Player.create(name: "Trevor Linden", rating: 78, position: "F")
    Player.create(name: "Peter Bondra", rating: 78, position: "F")
    Player.create(name: "Benoit Hogue", rating: 78, position: "F")
    Player.create(name: "Alexei Zhamnov", rating: 78, position: "F")
    Player.create(name: "Kevin Stevens", rating: 77, position: "F")
    Player.create(name: "Petr Klima", rating: 76, position: "F")
    Player.create(name: "Jimmy Carson", rating: 76, position: "F")
    Player.create(name: "Brendan Shanahan", rating: 76, position: "F")
    Player.create(name: "Cliff Ronning", rating: 76, position: "F")
    Player.create(name: "Tony Granato", rating: 75, position: "F")
    Player.create(name: "Dimitri Khristich", rating: 75, position: "F")
    Player.create(name: "Denis Savard", rating: 75, position: "F")
    Player.create(name: "Pelle Eklund", rating: 75, position: "F")
    Player.create(name: "Rod Brind'Amour", rating: 75, position: "F")
    Player.create(name: "Ron Francis", rating: 75, position: "F")
    Player.create(name: "Craig Janney", rating: 75, position: "F")
    Player.create(name: "Dave Gagner", rating: 75, position: "F")
    Player.create(name: "Paul Ysebaert", rating: 74, position: "F")
    Player.create(name: "Pat Verbeek", rating: 74, position: "F")
    Player.create(name: "Stephan Lebeau", rating: 74, position: "F")
    Player.create(name: "Brian Bellows", rating: 74, position: "F")
    Player.create(name: "Vincent Damphousse", rating: 74, position: "F")
    Player.create(name: "Joe Nieuwendyk", rating: 74, position: "F")
    Player.create(name: "Dale Hawerchuk", rating: 74, position: "F")
    Player.create(name: "Russ Courtnall", rating: 73, position: "F")
    Player.create(name: "Geoff Sanderson", rating: 73, position: "F")
    Player.create(name: "Mike Ridley", rating: 73, position: "F")
    Player.create(name: "Thomas Steen", rating: 73, position: "F")
    Player.create(name: "Alexander Semak", rating: 73, position: "F")
    Player.create(name: "Joe Mullen", rating: 73, position: "F")
    Player.create(name: "Valeri Kamensky", rating: 73, position: "F")
    Player.create(name: "Mike Ricci", rating: 73, position: "F")
    Player.create(name: "Geoff Courtnall", rating: 73, position: "F")
    Player.create(name: "Robert Reichel", rating: 73, position: "F")
    Player.create(name: "Sergei Makarov", rating: 73, position: "F")
    Player.create(name: "Joe Juneau", rating: 72, position: "F")
    Player.create(name: "Christian Ruutu", rating: 72, position: "F")
    Player.create(name: "Stephane Richer", rating: 72, position: "F")
    Player.create(name: "Steve Thomas", rating: 72, position: "F")
    Player.create(name: "Sergei Nemchinov", rating: 72, position: "F")
    Player.create(name: "Dave Andreychuk", rating: 72, position: "F")
    Player.create(name: "Shayne Corson", rating: 71, position: "F")
    Player.create(name: "Glenn Anderson", rating: 71, position: "F")
    Player.create(name: "Nikolai Borschevsky", rating: 71, position: "F")
    Player.create(name: "Brent Sutter", rating: 71, position: "F")
    Player.create(name: "Joe Murphy", rating: 71, position: "F")
    Player.create(name: "Joel Otto", rating: 71, position: "F")
    Player.create(name: "Owen Nolan", rating: 71, position: "F")
    Player.create(name: "Brian Bradley", rating: 71, position: "F")
    Player.create(name: "John Cullen", rating: 70, position: "F")
    Player.create(name: "Greg Adams", rating: 70, position: "F")
    Player.create(name: "Jari Kurri", rating: 70, position: "F")
    Player.create(name: "Peter Stastny", rating: 70, position: "F")
    Player.create(name: "Darren Turcotte", rating: 70, position: "F")
    Player.create(name: "Nelson Emerson", rating: 70, position: "F")

    Player.create(name: "Ray Bourque", rating: 99, position: "D")
    Player.create(name: "Chris Chelios", rating: 84, position: "D")
    Player.create(name: "Phil Housley", rating: 84, position: "D")
    Player.create(name: "Paul Coffey", rating: 83, position: "D")
    Player.create(name: "Gary Suter", rating: 81, position: "D")
    Player.create(name: "Zarley Zalapski", rating: 80, position: "D")
    Player.create(name: "Al Iafrate", rating: 78, position: "D")
    Player.create(name: "Scott Stevens", rating: 76, position: "D")
    Player.create(name: "Brian Leetch", rating: 76, position: "D")
    Player.create(name: "Dave Manson", rating: 74, position: "D")
    Player.create(name: "Larry Murphy", rating: 74, position: "D")
    Player.create(name: "Al MacInnis", rating: 73, position: "D")
    Player.create(name: "Steve Smith", rating: 72, position: "D")
    Player.create(name: "Rob Blake", rating: 72, position: "D")
    Player.create(name: "Kevin Hatcher", rating: 72, position: "D")
    Player.create(name: "Steve Duchesne", rating: 72, position: "D")
    Player.create(name: "Dave Ellett", rating: 72, position: "D")
    Player.create(name: "Don Sweeney", rating: 71, position: "D")
    Player.create(name: "Jeff Brown", rating: 71, position: "D")
    Player.create(name: "James Patrick", rating: 71, position: "D")
    Player.create(name: "Steve Chiasson", rating: 68, position: "D")
    Player.create(name: "Teppo Numminen", rating: 68, position: "D")
    Player.create(name: "Ulf Samuelsson", rating: 68, position: "D")
    Player.create(name: "Eric Desjardins", rating: 68, position: "D")
    Player.create(name: "Nicklas Lidstrom", rating: 66, position: "D")
    Player.create(name: "Calle Johansson", rating: 66, position: "D")
    Player.create(name: "Mathieu Schneider", rating: 66, position: "D")
    Player.create(name: "Alexei Zhitnik", rating: 66, position: "D")
    Player.create(name: "Igor Kravchuk", rating: 66, position: "D")
    Player.create(name: "Mark Tinordi", rating: 65, position: "D")
    Player.create(name: "Doug Wilson", rating: 65, position: "D")
    Player.create(name: "Petr Svoboda", rating: 65, position: "D")
   
    Player.create(name: "Ed Belfour", rating: 98, position: "G")
    Player.create(name: "Patrick Roy", rating: 94, position: "G")
    Player.create(name: "Grant Fuhr", rating: 85, position: "G")
    Player.create(name: "Felix Potvin", rating: 79, position: "G")
    Player.create(name: "Curtis Joseph", rating: 77, position: "G")
    Player.create(name: "Bob Essensa", rating: 74, position: "G")
    Player.create(name: "Tom Barrasso", rating: 74, position: "G")
    Player.create(name: "Tommy Soderstrom", rating: 72, position: "G")
    Player.create(name: "Tim Cheveldae", rating: 69, position: "G")
    Player.create(name: "Kirk McLean", rating: 68, position: "G")
    Player.create(name: "Ron Hextall", rating: 68, position: "G")
    Player.create(name: "Bill Ranford", rating: 66, position: "G")
    Player.create(name: "Mike Vernon", rating: 63, position: "G")
    Player.create(name: "John Blue", rating: 63, position: "G")
    Player.create(name: "John Vanbiesbrouck", rating: 63, position: "G")
    Player.create(name: "Mike Richter", rating: 61, position: "G")
    Player.create(name: "Chris Terreri", rating: 61, position: "G")
    Player.create(name: "Sean Burke", rating: 61, position: "G")


